### ISSUE TITLE
Which files should be ignored?

### ISSUE THREAD

**Issue by takuti** [Sushisushi-sandesu/UnityWebCamSample#2]
`.gitignore` of the official sample project actually has many ignored files.

https://github.com/leapmotion-examples/LeapMotionWidgets/blob/master/.gitignore

僕らの .gitignore は今のままで大丈夫ですかね？

**Comment by natezzz** [comment]
I'm really not sure what to ignore because it might not run on other members' machines if I accidentally excluded some important files.

But I think the Tmp directory is safe to be ignored :+1: 
今のままで大丈夫でしょう

**Comment by takuti** [comment]
今日Unityを触ってみましたが、大丈夫じゃないような気がします :cry: 月曜日にまた話しましょう！

**Comment by takuti** [comment]
とりあえず解決ということで、closeしますー。作業中に気づいた点があれば適宜updateしましょう。
